repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: format
        name: Format
        entry: make
        args: [format]
        types_or: [python, ts, javascript, json, html, css]
        language: system
        pass_filenames: false
      - id: lint
        name: Lint
        entry: make
        args: [lint]
        types_or: [python, ts, javascript, json, html, css]
        language: system
        pass_filenames: false
      - id: typecheck
        name: Typecheck
        entry: make
        args: [typecheck]
        types_or: [ts, javascript, json, html]
        language: system
        pass_filenames: false
